// <auto-generated />
namespace Classified.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class CreateFunc_FetchClassifiedAdsAttributesInDatabase : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CreateFunc_FetchClassifiedAdsAttributesInDatabase));
        
        string IMigrationMetadata.Id
        {
            get { return "201809221246343_CreateFunc_FetchClassifiedAdsAttributesInDatabase"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
