namespace Classified.Web.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class populateClassifiedAttributeValuesTableInitialValues : DbMigration
    {
        public override void Up()
        {
            Sql(@"SET IDENTITY_INSERT [dbo].[ClassifiedCategoryAttributeValues] ON
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (1, 7, N'Siamese')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (2, 7, N'Kitten')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (4, 7, N'Birman')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (5, 7, N'Bengal')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (6, 7, N'Himalayan')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (7, 14, N'Css')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (8, 14, N'Html')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (9, 14, N'Flash')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (10, 14, N'DreamWeaver')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (11, 14, N'Java')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (12, 14, N'JavaScript')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (13, 14, N'PHP')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (14, 10, N'Slender')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (15, 10, N'Athletic')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (16, 10, N'Average')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (17, 10, N'A Little Extra')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (18, 10, N'More to Love')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (19, 9, N'130-135')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (20, 9, N'135-140')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (21, 9, N'140-145')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (22, 9, N'145-150')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (23, 11, N'Asian')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (24, 11, N'Black/African')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (25, 11, N'Caucasain')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (26, 11, N'East India')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (27, 11, N'Latino/Hispanic')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (28, 11, N'Middle Eastern')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (50, 17, N'2-door')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (51, 17, N'4-door')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (52, 17, N'Convertible')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (53, 17, N'Pipup Trucks')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (54, 17, N'Sport Utility Vehicle(SUV)')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (55, 17, N'Van And MiniVans')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (56, 18, N'2012')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (57, 18, N'2011')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (58, 18, N'2010')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (59, 18, N'2009')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (60, 18, N'2008')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (61, 18, N'2007')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (62, 18, N'2006')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (63, 18, N'2005')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (64, 18, N'2004')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (65, 18, N'2003')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (66, 18, N'2002')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (67, 19, N'CL')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (68, 19, N'EL')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (69, 19, N'MDX')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (70, 19, N'NDX')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (71, 20, N'Defender')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (72, 20, N'Decovery')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (73, 20, N'FreeLander')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (74, 20, N'Rang Rover')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (75, 21, N'New')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (76, 21, N'Used')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (77, 23, N'1')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (78, 23, N'2')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (81, 7, N'Exotic')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (82, 7, N'Hybrid')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (83, 7, N'Persian')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (87, 7, N'Other')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (90, 26, N'Cages')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (91, 26, N'Chews')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (92, 26, N'Cloths')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (93, 26, N'Collars')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (94, 26, N'Food')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (95, 26, N'Health')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (96, 26, N'Hygiene')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (97, 26, N'Leash')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (98, 26, N'NeckLeces')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (99, 26, N'Saddles')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (100, 26, N'Tanks')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (101, 26, N'Ties')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (102, 26, N'Toys')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (103, 26, N'Other')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (104, 27, N'Buff Cochins')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (105, 27, N'Cardinal')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (106, 27, N'Chickens')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (107, 27, N'Chicks')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (108, 27, N'Cockatiel')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (109, 27, N'Ducks')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (110, 27, N'Eggs')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (111, 27, N'Hens')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (112, 27, N'Parakeet')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (113, 27, N'Peacocks')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (114, 27, N'Pheasants')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (115, 27, N'Pigeons')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (116, 27, N'Quails')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (117, 27, N'Silkies')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (118, 27, N'Turkeys')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (119, 27, N'Other')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (120, 28, N'Afghand Hound')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (121, 28, N'Akita')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (122, 28, N'Alaskan Malamute')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (123, 28, N'Basset Hound')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (124, 28, N'Beagle')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (125, 28, N'Bichon Frise')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (126, 28, N'Border Collie')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (127, 28, N'Boxer')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (128, 28, N'Bulldog')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (129, 28, N'Bull Terrier')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (130, 28, N'Chihuahua')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (131, 28, N'Chow Chow')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (132, 28, N'Cocker')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (133, 28, N'Collie')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (134, 28, N'Dachshund')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (135, 28, N'Dalmatian')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (136, 28, N'Doberman')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (137, 28, N'French Bulldog')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (138, 28, N'Golden Retriever')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (139, 28, N'Great Dane')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (140, 28, N'Irish Setter')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (141, 28, N'Jack Russell')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (142, 28, N'Labrador')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (143, 28, N'Lhasa Apso')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (144, 28, N'Maltese')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (145, 28, N'Mastiff')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (146, 28, N'Miniature Pinscher')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (147, 28, N'Pekingese')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (148, 28, N'Pitbull')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (149, 28, N'Pointer')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (150, 28, N'Pomeranian')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (151, 28, N'Pug')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (152, 28, N'Rottweiler')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (153, 28, N'Saint Bernard')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (154, 28, N'Sharpei')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (155, 28, N'Shizhtzu')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (156, 28, N'Siberian Husky')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (157, 28, N'Other')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (158, 29, N'Albinos')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (159, 29, N'Arowanas')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (160, 29, N'Buffer')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (161, 29, N'Carps')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (162, 29, N'Catfishes')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (163, 29, N'Discus')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (164, 29, N'Dragon')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (165, 29, N'Exotics')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (166, 29, N'Fighter')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (167, 29, N'Flowerhorns')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (168, 29, N'Gold')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (169, 29, N'Kamfa')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (170, 29, N'Lion')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (171, 29, N'Ornamental')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (172, 29, N'Oscar')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (173, 29, N'Other')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (174, 30, N'Kathiawad')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (175, 30, N'Marwari')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (176, 30, N'Nukra')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (177, 30, N'Phonys')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (178, 30, N'Z Black')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (179, 30, N'Other')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (180, 31, N'Hamsters')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (181, 31, N'Mice')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (182, 31, N'Other')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (183, 33, N'Bags')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (184, 33, N'Batteries')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (185, 33, N'Cables')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (186, 33, N'Cleaning')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (187, 33, N'Flashes')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (188, 33, N'Grips')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (189, 33, N'Manuals')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (190, 33, N'Memory Cards')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (191, 33, N'MircroPhones')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (192, 33, N'Software')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (193, 33, N'Tapes')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (194, 33, N'Tripods')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (195, 33, N'Under Water Cases')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (196, 33, N'Other')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (197, 34, N'Compact')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (198, 34, N'Pocket')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (199, 34, N'Professional')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (200, 34, N'Other')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (201, 35, N'3D')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (202, 35, N'DVD')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (203, 35, N'Flash Memory')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (204, 35, N'Full HD')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (205, 35, N'HDD')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (206, 35, N'MiniDV')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (207, 35, N'Standard Definitaion')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (208, 35, N'Other')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (209, 36, N'Aiptek')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (210, 36, N'Argus')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (211, 36, N'BenQ')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (212, 36, N'Canon')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (213, 36, N'Casio')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (214, 36, N'Epson')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (215, 36, N'Fujifilm')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (216, 36, N'Gateway')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (217, 36, N'GE')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (218, 36, N'Hitachi')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (219, 36, N'HP')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (220, 36, N'Insignia')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (221, 36, N'JVC')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (222, 36, N'Kodak')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (223, 36, N'Konica')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (224, 36, N'Leica')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (225, 36, N'Memorex')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (226, 36, N'Minolta')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (227, 36, N'Minox')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (228, 36, N'Mustek')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (229, 36, N'Samsung')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (230, 36, N'Sony')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (231, 36, N'Toshiba')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (232, 37, N'Canon')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (233, 37, N'Kodak')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (234, 37, N'Minolta')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (235, 37, N'Nikon')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (236, 37, N'Olympus')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (237, 37, N'Pentax')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (238, 37, N'Sony')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (239, 37, N'Yashica')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (248, 39, N'Cameras')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (249, 40, N'Basic')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (250, 40, N'Advanced')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (251, 42, N'Cameras')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (252, 44, N'Collections')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (253, 44, N'Nepali Music')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (254, 44, N'Movies')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (255, 44, N'Music')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (256, 45, N'Blues')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (257, 45, N'Children')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (258, 45, N'Classical')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (259, 45, N'Collections')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (260, 45, N'Dance')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (261, 45, N'English')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (262, 45, N'Funk')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (263, 45, N'Gospel')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (264, 45, N'Jazz')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (265, 45, N'Karaoke')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (266, 45, N'Romantic')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (267, 46, N'Black Music')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (268, 46, N'Blues')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (269, 46, N'Classical')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (270, 48, N'BackPacks')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (271, 48, N'Bags')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (272, 48, N'Belts')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (273, 48, N'Cases')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (274, 48, N'Gloves')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (275, 48, N'Hair')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (276, 48, N'Hats')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (277, 48, N'Purses')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (278, 48, N'Scarves')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (279, 48, N'Sunglasses')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (280, 48, N'Wallets')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (281, 49, N'Bermudas')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (282, 49, N'Blazers')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (283, 49, N'BoardShorts')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (284, 49, N'Cardigans')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (285, 49, N'Coats')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (286, 49, N'Hoodies')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (287, 49, N'jackets')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (288, 49, N'jeans')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (289, 49, N'Kurta')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (290, 49, N'Pants')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (291, 49, N'Polos')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (292, 49, N'Raincoats')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (293, 49, N'Sherwani')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (294, 49, N'Shirts')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (295, 49, N'Shorts')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (296, 49, N'Sleepwear')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (297, 50, N'Boats')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (298, 50, N'Casual')
                    INSERT INTO [dbo].[ClassifiedCategoryAttributeValues] ([Id], [ClassifiedCategoryAttributeId], [AttributeValue]) VALUES (299, 50, N'Formal')
                SET IDENTITY_INSERT [dbo].[ClassifiedCategoryAttributeValues] OFF
                ");
        }
        
        public override void Down()
        {
        }
    }
}
